### ISSUE TITLE
JS isn't loaded for API version 2

### ISSUE THREAD

**Issue by Mabahe** [mblaschke/TYPO3-jm-recaptcha#5]
See https://developers.google.com/recaptcha/docs/display

**Comment by Mabahe** [comment]
There is already PR #3 and will push a optimized version.

**Comment by vaxul** [comment]
@Mabahe 
Thanks for the hint. I hope it get merged. (For now I have to add it manually)

And I have an addition to it, since I didn't know if it's possible to create a pull request which inherit from a pull request:
The JavaScript for the API is lacking of the language parameter. My suggestion to it:
`$content = '<script type="text/javascript" src="' . htmlspecialchars($this->conf['server']) . '.js?hl=' . htmlspecialchars($this->conf['lang']) . '"></script>';`

And the div-tag is lacking of the theme parameter. My suggestion to it:
`$content .= '<div class="g-recaptcha" data-sitekey="' . htmlspecialchars($this->conf['public_key']) . '" data-theme="' . htmlspecialchars($this->conf['theme']) . '"></div>';`

And the new detail in the TypoScript constants should be empty.

[Docs](https://developers.google.com/recaptcha/docs/display)

**Comment by vaxul** [comment]
I added a new pull request #7 with all missing parameters.

**Comment by vaxul** [comment]
In my opinion, this issue can be closed.
